### PR TITLE
Update config, update NLog

### PR DESCRIPTION
**Pull request by 304NotModified**
See #1

### CODE REVIEW

**Comment by PureKrome** [comment]
Out of interest, this would mean the Readme.md would also need to be updated because the NLog stats would now be different?

Is that to be part of this PR or for @wddpct to merge, run, get stats, update readme (outside of this PR)?

(i also get/understand that all the stats would need to be re-run because it's each machine is different and it's really more about the trend/differences/rough numbers vs the actual exact numbers)

**Comment by 304NotModified** [comment]
> Out of interest, this would mean the Readme.md would also need to be updated because the NLog stats would now be different?

yes, but I have a different machine ;)



> Is that to be part of this PR or for @wddpct to merge, run, get stats, update readme (outside of this PR)?

I think it's the best that  @wddpct  run the stats - it's more independent.

**Comment by PureKrome** [comment]
Cheers and agreed 👍 ta!

**Comment by 304NotModified** [comment]
> ### [304NotModified](/304NotModified) referenced this pull request [ a day ago ](#ref-pullrequest-363275982)
>  Merged
> #### [ Added aspnet-request-form info to layout-renderers.json #73](/NLog/NLog.github.io/pull/73)

Lol wrong copy-paste 👼

**Comment by panchengtao** [comment]
@304NotModified thanks, and sorry for my negligence. I may rebuild the benchmark later soon.

**Pull request merged**
